### ISSUE TITLE
Tempura and familly conflicting with timbre

### ISSUE THREAD

**Issue by Kaspazza** [taoensso/timbre#392]
Hi, I know this is a issue not exactly with current timbre, but it's with taoensso library using old timbre. 
I'm not sure if the tempura issues are looked at so I want to reference this one: https://github.com/taoensso/tempura/issues/37

**Comment by ptaoussanis** [comment]
@Kaspazza Hi Mateusz, have you tried using the newest version of Encore?
https://www.taoensso.com/dependency-conflicts may be helpful if you're seeing a conflict.

**Comment by Kaspazza** [comment]
Yes, what helps with most of the messages is to include timbre in my deps (even though we don't use it in our project, so it is a little bit weird to put it in the dependencies).

I've updated now everything to the newest version, and excluded the libraries so it uses my project version. 
```
com.taoensso/encore {:exclusions [com.taoensso/timbre]
                             :mvn/version "3.132.0"}
        com.taoensso/sente {:exclusions [com.taoensso/encore com.taoensso/timbre]
                            :mvn/version "1.19.2"}
        com.taoensso/tempura {:exclusions
                              [com.taoensso/encore com.taoensso/timbre com.taoensso/sente]
                              :mvn/version "1.5.4"}
        com.taoensso/timbre {:mvn/version "6.6.1"}
```
 
But still one warning remains:
<img width="988" alt="image" src="https://github.com/user-attachments/assets/8e8e9a37-dcc3-4f71-bfba-a042340b7667">

**Comment by ptaoussanis** [comment]
> Yes, what helps with most of the messages is to include timbre in my deps (even though we don't use it in our project, so it is a little bit weird to put it in the dependencies).

If you're using Sente, then Timbre is pulled in as a transitive dependency.
You can use `lein deps :tree` (or equivalent) to see your full dependency chain.

> But still one warning remains

This is just a deprecation warning and can be safely ignored for now. It'll disappear when the next version of Sente is released.

Hope that helps!

**Comment by Kaspazza** [comment]
Yeah, I know it's only deprecation warning, it's just strange to get those warnings that are unrelated to our code in shadow-cljs as we try to keep it clean and green ;).

Thanks for response, I will wait for new version.

**Comment by Kaspazza** [comment]
Oh okay, the 1.20.0-RC1 for sente is available, using that version warning disappears. Thanks!
